# Site settings
name: kz font gallery
title: kz Font Gallery
description: "Font Gallery for EMUI by berkantkz"
baseurl: ""
author: berkantkz
repository: berkantkz/kzfontgallery
exclude: ["tools"]

# Build settings
markdown: kramdown
permalinks: pretty